#!/bin/sh
# postrm for egressdns

set -e

case "$1" in
    purge)
        rm -rf /var/lib/egressdns
        rm -rf /etc/egressdns
        if getent passwd egressdns >/dev/null; then
            deluser --system egressdns >/dev/null 2>&1 || true
        fi
        if getent group egressdns >/dev/null; then
            delgroup --system egressdns >/dev/null 2>&1 || true
        fi
        ;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;
    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#

exit 0
